version: '3'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb

  flaskapp:
    build: ./flask_app
    ports:
      - "5000:5000"
    depends_on:
      - influxdb
